# Configuration for semantic versioning
# Used by mathieudutour/github-tag-action

# Enable title-only conventional commits parsing
titleOnly: true

# Specify the types that will trigger a version bump
types:
  - feat       # Bumps minor version (0.1.0 -> 0.2.0)
  - fix        # Bumps patch version (0.1.0 -> 0.1.1)
  - perf       # Bumps patch version
  - revert     # Bumps patch version
  - docs       # Does not bump the version
  - style      # Does not bump the version
  - refactor   # Does not bump the version
  - build      # Does not bump the version
  - ci         # Does not bump the version
  - test       # Does not bump the version
  - chore      # Does not bump the version

# Specify which types trigger different version bumps
major:
  # A breaking change will trigger a major version bump (0.1.0 -> 1.0.0)
  - breaking
  - BREAKING CHANGE
  
minor:
  # A feat type will trigger a minor version bump
  - feat
  
patch:
  # These types will trigger a patch version bump
  - fix
  - perf
  - revert 