name: Update Badges

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Test with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Calculate code coverage percentage
        id: coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "Current coverage: $COVERAGE%"

      # Method 1: Use direct GitHub API to update the gist
      - name: Update coverage gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_TOKEN: ${{ secrets.GIST_SECRET }}
        run: |
          # Create JSON payload for the gist content
          cat > coverage.json << EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${{ env.COVERAGE }}%",
            "color": "${{ env.COVERAGE >= 80 && 'green' || env.COVERAGE >= 70 && 'yellow' || 'red' }}"
          }
          EOF
          
          # Update the gist
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"files\":{\"mail-api-coverage.json\":{\"content\":$(cat coverage.json | jq -R -s .)}}" \
            "https://api.github.com/gists/$GIST_ID"

      # Method 2: Use a simpler action as fallback
      - name: Create simple coverage badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          LABEL: 'coverage'
          STATUS: '${{ env.COVERAGE }}%'
          COLOR: ${{ env.COVERAGE >= 80 && '5cb85c' || env.COVERAGE >= 70 && 'f0ad4e' || 'e05d44' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Go Report Card badge
        uses: creekorful/goreportcard-action@v1.0 